# Generated by Django 4.2.6 on 2023-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, unique=True)),
                ('o_hours', models.CharField(max_length=100)),
            ],
        ),
    ]
